language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
sudo: false
# command to install dependencies
install:
  - pip install tox tox-travis
# command to run tests
script:
  - tox
